<a href="https://colab.research.google.com/github/tarisahmad/TgsDataMining/blob/main/Preprocessing_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

numpy merupakan library python digunakan untuk komputasi matriks.
Matloplib merupakan library python untuk
presentasi data berupa grafik atau plot. . . . .

In [2]:
dataset = pd.read_csv('data_covid2.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print(x)

In [ ]:
print(x)

[['Turkey' 13913625 142875926.0 145454202.0 52786023.0 31.6 12.13]
 ['Turkey' 13975389 143297781.0 145503292.0 52792845.0 31.6 12.13]
 ['Turkey' 14025181 143692044.0 145537442.0 52797530.0 31.6 12.13]
 ['Turkey' 14089456 144102479.0 145631632.0 52809698.0 31.6 12.13]
 ['Turks and Caicos Islands' 5860 nan 68176.0 29160.0 nan nan]
 ['Turks and Caicos Islands' 5860 nan nan nan nan nan]
 ['Turks and Caicos Islands' 5860 nan nan nan nan nan]
 ['Turks and Caicos Islands' 5867 nan nan nan nan nan]
 ['Uganda' 163231 nan nan nan 16.4 2.5]
 ['Uganda' 163231 2452572.0 nan nan 16.4 2.5]
 ['Uganda' 163250 2457240.0 nan nan 16.4 2.5]
 ['Uganda' 163307 nan 16672943.0 7679657.0 16.4 2.5]
 ['Ukraine' 5040518 nan nan nan 41.4 7.11]
 ['Ukraine' 5040518 nan nan nan 41.4 7.11]
 ['Ukraine' 5040518 nan nan nan 41.4 7.11]
 ['Ukraine' 5040518 nan nan nan 41.4 7.11]
 ['United Arab Emirates' 878102 136398177.0 24079969.0 9465039.0 34.0
  17.26]
 ['United Arab Emirates' 878746 136846006.0 24090450.0 nan 34.0 17.2

In [ ]:
print(y)

[ 93805  94026  94232  94445     36     36     36     36   3585   3585
   3588   3588 112459 112459 112459 112459   2300   2301   2301   2301
 161367 161367 161367 161504]


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:8])
x[:, 1:8] = imputer.transform(x[:, 1:8])

print(x)

In [ ]:
print(x)

[['Turkey' 13913625.0 142875926.0 145454202.0 52786023.0 31.6 12.13]
 ['Turkey' 13975389.0 143297781.0 145503292.0 52792845.0 31.6 12.13]
 ['Turkey' 14025181.0 143692044.0 145537442.0 52797530.0 31.6 12.13]
 ['Turkey' 14089456.0 144102479.0 145631632.0 52809698.0 31.6 12.13]
 ['Turks and Caicos Islands' 5860.0 212978895.5 68176.0 29160.0
  32.839999999999996 8.656]
 ['Turks and Caicos Islands' 5860.0 212978895.5 89610655.28571428
  34099572.15384615 32.839999999999996 8.656]
 ['Turks and Caicos Islands' 5860.0 212978895.5 89610655.28571428
  34099572.15384615 32.839999999999996 8.656]
 ['Turks and Caicos Islands' 5867.0 212978895.5 89610655.28571428
  34099572.15384615 32.839999999999996 8.656]
 ['Uganda' 163231.0 212978895.5 89610655.28571428 34099572.15384615 16.4
  2.5]
 ['Uganda' 163231.0 2452572.0 89610655.28571428 34099572.15384615 16.4
  2.5]
 ['Uganda' 163250.0 2457240.0 89610655.28571428 34099572.15384615 16.4
  2.5]
 ['Uganda' 163307.0 212978895.5 16672943.0 7679657.0 16.4 2.

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 0.0 0.0 0.0 13913625.0 142875926.0 145454202.0 52786023.0
  31.6 12.13]
 [1.0 0.0 0.0 0.0 0.0 0.0 13975389.0 143297781.0 145503292.0 52792845.0
  31.6 12.13]
 [1.0 0.0 0.0 0.0 0.0 0.0 14025181.0 143692044.0 145537442.0 52797530.0
  31.6 12.13]
 [1.0 0.0 0.0 0.0 0.0 0.0 14089456.0 144102479.0 145631632.0 52809698.0
  31.6 12.13]
 [0.0 1.0 0.0 0.0 0.0 0.0 5860.0 212978895.5 68176.0 29160.0
  32.839999999999996 8.656]
 [0.0 1.0 0.0 0.0 0.0 0.0 5860.0 212978895.5 89610655.28571428
  34099572.15384615 32.839999999999996 8.656]
 [0.0 1.0 0.0 0.0 0.0 0.0 5860.0 212978895.5 89610655.28571428
  34099572.15384615 32.839999999999996 8.656]
 [0.0 1.0 0.0 0.0 0.0 0.0 5867.0 212978895.5 89610655.28571428
  34099572.15384615 32.839999999999996 8.656]
 [0.0 0.0 1.0 0.0 0.0 0.0 163231.0 212978895.5 89610655.28571428
  34099572.15384615 16.4 2.5]
 [0.0 0.0 1.0 0.0 0.0 0.0 163231.0 2452572.0 89610655.28571428
  34099572.15384615 16.4 2.5]
 [0.0 0.0 1.0 0.0 0.0 0.0 163250.0 2457240.0 8961065

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

print(y)

In [ ]:
print(y)

[ 5  6  7  8  0  0  0  0  3  3  4  4  9  9  9  9  1  2  2  2 10 10 10 11]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

print(x_train)

In [ ]:
print(x_train)

[[0.0 0.0 0.0 0.0 1.0 0.0 878746.0 136846006.0 24090450.0
  34099572.15384615 34.0 17.26]
 [0.0 0.0 1.0 0.0 0.0 0.0 163250.0 2457240.0 89610655.28571428
  34099572.15384615 16.4 2.5]
 [0.0 1.0 0.0 0.0 0.0 0.0 5860.0 212978895.5 68176.0 29160.0
  32.839999999999996 8.656]
 [1.0 0.0 0.0 0.0 0.0 0.0 14025181.0 143692044.0 145537442.0 52797530.0
  31.6 12.13]
 [0.0 0.0 0.0 0.0 1.0 0.0 879973.0 137716535.0 24119061.0 9485024.0 34.0
  17.26]
 [0.0 1.0 0.0 0.0 0.0 0.0 5860.0 212978895.5 89610655.28571428
  34099572.15384615 32.839999999999996 8.656]
 [0.0 1.0 0.0 0.0 0.0 0.0 5867.0 212978895.5 89610655.28571428
  34099572.15384615 32.839999999999996 8.656]
 [0.0 0.0 0.0 0.0 0.0 1.0 18854972.0 463318271.0 139809636.0 48989616.0
  40.8 4.28]
 [1.0 0.0 0.0 0.0 0.0 0.0 13975389.0 143297781.0 145503292.0 52792845.0
  31.6 12.13]
 [0.0 0.0 0.0 0.0 1.0 0.0 878102.0 136398177.0 24079969.0 9465039.0 34.0
  17.26]
 [1.0 0.0 0.0 0.0 0.0 0.0 13913625.0 142875926.0 145454202.0 52786023.0
  31.6 12.13]
 [0

print(x_test)

In [ ]:
print(x_test)

[[0.0 0.0 0.0 1.0 0.0 0.0 5040518.0 212978895.5 89610655.28571428
  34099572.15384615 41.4 7.11]
 [0.0 0.0 0.0 0.0 1.0 0.0 879368.0 137299003.0 24105222.0 9475136.0 34.0
  17.26]
 [1.0 0.0 0.0 0.0 0.0 0.0 14089456.0 144102479.0 145631632.0 52809698.0
  31.6 12.13]
 [0.0 0.0 0.0 1.0 0.0 0.0 5040518.0 212978895.5 89610655.28571428
  34099572.15384615 41.4 7.11]
 [0.0 0.0 0.0 0.0 0.0 1.0 18854972.0 462839786.0 139752045.0 48969964.0
  40.8 4.28]]


print(y_train)

In [ ]:
print(y_train)

[ 2  4  0  7  2  0  0 10  6  1  5  9 11 10  3  3  9  4  0]


print(y_test)

In [ ]:
print(y_test)

[ 9  2  8  9 10]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 8:] = sc.fit_transform(x_train[:, 8:])
x_test[:, 8:] = sc.transform(x_test[:,8:])

print(x_train)

In [ ]:
print(x_train)

[[0.0 0.0 0.0 -0.3429971702850177 2.309401076758503 -0.4330127018922193
  -0.6748177498502026 -0.5536668676531387 -1.3312361197378355
  0.029713078103587056 0.2890945775450186 1.7768467930858634]
 [0.0 0.0 1.0 -0.3429971702850177 -0.4330127018922193 -0.4330127018922193
  -0.7711206996312135 -1.6077260071052468 0.04494499740321487
  0.029713078103587056 -1.7660335417375959 -1.1877006091546534]
 [0.0 1.0 0.0 -0.3429971702850177 -0.4330127018922193 -0.4330127018922193
  -0.7923047751061754 0.043470604316597605 -1.8357980289294789
  -2.11792251978849 0.15364295150139134 0.04873257568224496]
 [1.0 0.0 0.0 -0.3429971702850177 -0.4330127018922193 -0.4330127018922193
  1.0946407371355034 -0.49997094397052644 1.219626723184623
  1.208342784634809 0.008849834006480463 0.7464858057217811]
 [0.0 0.0 0.0 -0.3429971702850177 2.309401076758503 -0.4330127018922193
  -0.6746526004721749 -0.5468389974678577 -1.3306351765971536
  -1.5218701432124213 0.2890945775450186 1.7768467930858634]
 [0.0 1.0 0.0 -0

print(x_test)

In [ ]:
print(x_test)

[[0.0 0.0 0.0 2.915475947422651 -0.4330127018922193 -0.4330127018922193
  -0.11465959394714019 0.043470604316597605 0.04494499740321487
  0.029713078103587056 1.1531825367888449 -0.26178167119199885]
 [0.0 0.0 0.0 -0.3429971702850177 2.309401076758503 -0.4330127018922193
  -0.6747340310945927 -0.5501138502231372 -1.33092584983905
  -1.5224934353726707 0.2890945775450186 1.7768467930858634]
 [1.0 0.0 0.0 -0.3429971702850177 -0.4330127018922193 -0.4330127018922193
  1.1032918995419663 -0.4967517555236214 1.2216050823618916
  1.2091097970747275 0.008849834006480463 0.7464858057217811]
 [0.0 0.0 0.0 2.915475947422651 -0.4330127018922193 -0.4330127018922193
  -0.11465959394714019 0.043470604316597605 0.04494499740321487
  0.029713078103587056 1.1531825367888449 -0.26178167119199885]
 [0.0 0.0 0.0 -0.3429971702850177 -0.4330127018922193 2.309401076758503
  1.744711625198859 2.0032189007119037 1.0981107103478862
  0.9670713565768593 1.0831213509042101 -0.8301874400497673]]
